import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  main: {
    flex: 1,
    backgroundColor: "#f8f8f8",
  },
  mainContent: {
    padding: 20,
    alignItems: "center",
    paddingTop: 60,
  },
  title: {
    fontSize: 24,
    color: "#333",
    fontWeight: "bold",
    fontFamily: 'latto-bold',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: "#666",
    marginBottom: 30,
    fontFamily: 'latto-light',
  },
  button: {
    backgroundColor: "#007AFF",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 10,
  },
  backButton: {
    backgroundColor: "#6C757D",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    fontFamily: 'latto-bold',
  },
  // News styles
  newsCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  newsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  newsCategory: {
    backgroundColor: "#007AFF",
    color: "#fff",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    fontSize: 12,
    fontFamily: 'latto-bold',
  },
  newsDate: {
    color: "#666",
    fontSize: 12,
    fontFamily: 'latto-light',
  },
  newsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 8,
    fontFamily: 'latto-bold',
  },
  newsSummary: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
    fontFamily: 'latto-light',
  },
  // Contact styles
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 16,
    fontFamily: 'latto-bold',
  },
  contactItem: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  contactType: {
    fontSize: 14,
    color: "#666",
    marginBottom: 4,
    fontFamily: 'latto-light',
  },
  contactValue: {
    fontSize: 16,
    color: "#007AFF",
    fontWeight: "bold",
    fontFamily: 'latto-bold',
  },
  teamMember: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  memberName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 4,
    fontFamily: 'latto-bold',
  },
  memberPosition: {
    fontSize: 14,
    color: "#666",
    marginBottom: 4,
    fontFamily: 'latto-light',
  },
  memberEmail: {
    fontSize: 14,
    color: "#007AFF",
    fontFamily: 'latto-light',
  },
  appDescription: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
    marginBottom: 12,
    fontFamily: 'latto-light',
  },
});
